# Định danh dự án
sonar.projectKey=laravel-standard
sonar.projectName=Laravel Standard
sonar.projectVersion=1.0

# Đường dẫn chứa source code cần quét (Bỏ qua vendor, node_modules)
sonar.sources=app,config,database,routes,resources
sonar.tests=tests

# Đường dẫn đến báo cáo coverage do PHPUnit sinh ra (QUAN TRỌNG)
sonar.php.coverage.reportPaths=coverage/clover.xml

# Loại trừ các thư mục không cần quét
sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/public/**