replicaCount: 1

# Cau hinh Docker Image
image:
  repository: 192.168.92.128:8088/laravel/website-du-lich
  pullPolicy: Always
  tag: "latest"

# Cau hinh Service (Network)
service:
  type: NodePort
  port: 80
  nodePort: 30080

ingress:
  enabled: false
  className: "nginx"
  annotations: {}
  hosts:
    - host: website-du-lich.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

# Tài nguyên CPU/RAM cho Pod
resources:
  limits:
    cpu: 300m
    memory: 385Mi
  requests:
    cpu: 50m
    memory: 128Mi

# Cau hinh configmap (ĐÃ XÓA SẠCH KHOẢNG TRẮNG THỪA)
config:
  appname: "website_Du_Lich"
  appEnv: "local"
  appDebug: "true"
  appUrl: "http://localhost"
  dbConnection: "mysql"
  dbHost: "10.99.119.181"
  dbPort: "3306"
  dbDatabase: "travella"
  logChannel: "stderr"
  logLevel: "debug"

# Cau hinh Secret (ĐÃ CẬP NHẬT APP_KEY THẬT)
secret:
  appKey: "base64:BgMIa/gFgWbECq9mpFiQ7gwYB7aEK2ZiF98RaV6RjHA="
  dbUser: "root"
  dbPassword: "root"