apiVersion: v1
kind: Secret
metadata: 
  name: {{ .Release.Name }}-secret
  labels:
    app: laravel-website
type: Opaque
stringData:
  APP_KEY: {{ .Values.secret.appKey }}
  DB_USER: {{ .Values.secret.dbUser }}
  DB_PASSWORD: {{ .Values.secret.dbPassword }}